service: opendatadr-partidos
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": OpenDataGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": OpenDataGW-rootResourceId
functions:
  get-partidos:
    handler: handler.getPartidos
    events:
      - http:
          path: /partidos
          method: get
