org: enzovezzaro
app: opendatadr
service: opendatadr-api-v1-estado
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource: "*"
  apiGateway:
    restApiId:
      "Fn::ImportValue": OpenDataGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": OpenDataGW-rootResourceId
plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    enabled: false
    events:
      - schedule: rate(5 minutes)
functions:
  get-municipios:
    handler: handler.getMunicipios
    events:
      - http:
          path: /estado/{year}/municipios
          method: get
          request:
            parameters:
              paths:
                year: true
              querystrings:
                start: false
                query: false
                value: false
    environment:
      ENDPOINT: ${file(../serverless.env.yml):${opt:stage}.ENDPOINT}
      PORT: ${file(../serverless.env.yml):${opt:stage}.PORT}
      DATABASE: ${file(../serverless.env.yml):${opt:stage}.DATABASE}
      USERNAME: ${file(../serverless.env.yml):${opt:stage}.USERNAME}
      PASSWORD: ${file(../serverless.env.yml):${opt:stage}.PASSWORD}
  get-distritos:
    handler: handler.getDistritos
    events:
      - http:
          path: /estado/{year}/distritos
          method: get
          request:
            parameters:
              paths:
                year: true
              querystrings:
                start: false
                query: false
                value: false
    environment:
      ENDPOINT: ${file(../serverless.env.yml):${opt:stage}.ENDPOINT}
      PORT: ${file(../serverless.env.yml):${opt:stage}.PORT}
      DATABASE: ${file(../serverless.env.yml):${opt:stage}.DATABASE}
      USERNAME: ${file(../serverless.env.yml):${opt:stage}.USERNAME}
      PASSWORD: ${file(../serverless.env.yml):${opt:stage}.PASSWORD}
  get-cargos:
    handler: handler.getCargos
    events:
      - http:
          path: /estado/{year}/cargos
          method: get
          request:
            parameters:
              paths:
                year: true
              querystrings:
                start: false
    environment:
      ENDPOINT: ${file(../serverless.env.yml):${opt:stage}.ENDPOINT}
      PORT: ${file(../serverless.env.yml):${opt:stage}.PORT}
      DATABASE: ${file(../serverless.env.yml):${opt:stage}.DATABASE}
      USERNAME: ${file(../serverless.env.yml):${opt:stage}.USERNAME}
      PASSWORD: ${file(../serverless.env.yml):${opt:stage}.PASSWORD}
  get-provincias:
    handler: handler.getProvincias
    events:
      - http:
          path: /estado/{year}/provincias
          method: get
          request:
            parameters:
              paths:
                year: true
              querystrings:
                start: false
    environment:
      ENDPOINT: ${file(../serverless.env.yml):${opt:stage}.ENDPOINT}
      PORT: ${file(../serverless.env.yml):${opt:stage}.PORT}
      DATABASE: ${file(../serverless.env.yml):${opt:stage}.DATABASE}
      USERNAME: ${file(../serverless.env.yml):${opt:stage}.USERNAME}
      PASSWORD: ${file(../serverless.env.yml):${opt:stage}.PASSWORD}
