org: enzovezzaro
app: opendatadr
service: mirex-api-v1-fijos
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource: "*"
  apiGateway:
    restApiId:
      "Fn::ImportValue": OpenDataGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": OpenDataGW-rootResourceId
plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    enabled: false
    events:
      - schedule: rate(5 minutes)
functions:
  get-partidos:
    handler: handler.getFijos
    events:
      - http:
          path: /fijos/{year}
          method: get
          request:
            parameters:
              paths:
                year: true
              querystrings:
                start: false
                query: false
                value: false
    environment:
        ENDPOINT: ${file(../serverless.env.yml):${opt:stage}.ENDPOINT}
        PORT: ${file(../serverless.env.yml):${opt:stage}.PORT}
        DATABASE: ${file(../serverless.env.yml):${opt:stage}.DATABASE}
        USERNAME: ${file(../serverless.env.yml):${opt:stage}.USERNAME}
        PASSWORD: ${file(../serverless.env.yml):${opt:stage}.PASSWORD}